import csv
import re
from clickhouse_connect import get_client
import os
import subprocess
from services.file_service import FileService
from datetime import datetime, timedelta

def get_unique_types_in_columns(file_path):
    with open(file_path, mode='r', encoding='utf-8') as csv_file:
        reader = csv.DictReader(csv_file, delimiter=';')
        column_types = {col: set() for col in reader.fieldnames}

        for row in reader:
            for col, value in row.items():
                column_upper = col.upper()
                if '_DATA_' in column_upper:
                    column_types[col].add('Nullable(Date)')
                    continue

                if value.isdigit():
                    column_types[col].add("Nullable(Int64)")
                else:
                    try:
                        float(value)
                        column_types[col].add("Nullable(Float64)")
                    except ValueError:
                        if re.match(r'\d{4}[-]\d{2}[-]\d{2}', value):
                            column_types[col].add("Nullable(Date)")
                        elif value.upper() in ('TRUE', 'FALSE'):
                            column_types[col].add("Nullable(Boolean)")
                        else:
                            column_types[col].add("Nullable(String)")

        query = ''
        for col, types in column_types.items():
            if 'Nullable(Date)' in types:
                types = 'Nullable(Date)'
            elif 'Nullable(Boolean)' in types:
                types = 'Nullable(Boolean)'
            elif 'Nullable(Int64)' in types and 'Nullable(String)' in types:
                types = 'Nullable(String)'
            elif 'Nullable(Float64)' in types and 'Nullable(String)' in types:
                types = 'Nullable(String)'
            elif 'Nullable(Float64)' in types:
                types = 'Nullable(Float64)'
            else:
                types = (next(iter(types)))
            query += (f"{col} {types}, ")

    query = query.replace('"', '')
    return query[1:-2]

def execute_command(command):
    result = subprocess.run(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        raise Exception(f"Error executing command: {result.stderr.decode()}")
    return result.stdout.decode()

def import_data(db_name, table_name, csv_path, username, password, port):
    command = f"""
    clickhouse-client --user={username} --password={password} --port={port} \
    --format_csv_delimiter=";" --format_csv_null_representation='\"\"' \
    --bool_true_representation='\"True\"' --bool_false_representation='\"False\"' \
    --query="INSERT INTO {db_name}.{table_name} FORMAT CSVWithNames" < {csv_path}
    """
    execute_command(command)

def create_or_truncate_combined_table(db_name, combined_table, client):
    query_exists = f"EXISTS TABLE {combined_table}"
    table_exists = client.command(query_exists) == 1

    '''
    Заготовленный скрипт
    SQL-запрос для получения всех колонок:
    WITH
        (SELECT groupArray(name) 
        FROM 
        (SELECT name 
            FROM system.columns 
            WHERE database = 'default' AND table = 'msc'
            UNION DISTINCT
            SELECT name 
            FROM system.columns 
            WHERE database = 'default' AND table = 'spb')) AS all_columns,
        (SELECT groupArray(name) 
        FROM 
        (SELECT name 
            FROM system.columns 
            WHERE database = 'default' AND table = 'msc')) AS msc_columns,
        (SELECT groupArray(name) 
        FROM 
        (SELECT name 
            FROM system.columns 
            WHERE database = 'default' AND table = 'spb')) AS spb_columns,
        (SELECT arrayMap((x, y) -> (if(has(msc_columns, x), x, concat('NULL AS ', y))), all_columns, all_columns)) as msc,
        (SELECT arrayMap((x, y) -> (if(has(spb_columns, x), x, concat('NULL AS ', y))), all_columns, all_columns)) as spb
    SELECT arrayStringConcat(arrayMap(x -> x, 'msc'), ',') --все колонки для msc
    SELECT arrayStringConcat(arrayMap(x -> x, 'spb'), ',') --все колонки для spb
    '''
    if table_exists:
        truncate_query = f"TRUNCATE TABLE {combined_table}"
        client.command(truncate_query)
        insert_query = f"""
        INSERT INTO {combined_table} (id,name,price,responsible_user,created_at,created_by,updated_at,updated_by,closed_at,tags,pipeline,status_id,contacts_0_id,contacts_0_name,contacts_0_responsible_user,contacts_0_contact_Dolzhnost,contacts_0_contact_Telefon,contacts_0_contact_Email,contacts_0_contact_Nomer_linii_MANGO_OFFICE,contacts_0_contact_Source_phone,contacts_0_contact_Whatsgroup_WZ,contacts_0_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kontakta,contacts_0_contact_Komment,contacts_0_companies_0_id,contacts_0_companies_0_name,contacts_0_companies_0_responsible_user,contacts_0_companies_0_company_Telefon,contacts_0_companies_0_company_Email,contacts_0_companies_0_company_Web,contacts_0_companies_0_company_Adres,etap_sdelki,companies_0_id,companies_0_name,companies_0_responsible_user,companies_0_company_Telefon,companies_0_company_Email,companies_0_company_Web,companies_0_company_Adres,lead_utm_content,lead_utm_medium,lead_utm_campaign,lead_utm_source,lead_utm_term,lead_utm_referrer,lead_roistat,lead_referrer,lead_openstat_service,lead_openstat_campaign,lead_openstat_ad,lead_openstat_source,lead_from,lead_gclientid,lead__ym_uid,lead__ym_counter,lead_gclid,lead_yclid,lead_fbclid,lead_ID_sajta_v_Calltouch,lead_ID_zvonka_v_Calltouch,lead_ID_zajavki_v_Calltouch,lead_Istochnik_utm_source,lead_Kanal_utm_medium,lead_Kampanija_utm_campaign,lead_Objavlenie_utm_content,lead_Kljuchevoe_slovo_utm_term,lead_Jandeks_Metrika,lead_Otslezhivaemyj_sajt,lead_Data_Zapis,lead_Data_Javka,lead_Data_PTsP,lead_Data_nachalo_lechenija,lead_Kategorija_dlja_OP,lead_PervichkaVtorichka,lead_Tip_obraschenija,lead_Data_1oj_konsultatsii,lead_Konsdoktor_perv_doktor,lead_Tip_konsultatsii,lead_Prichina_zakrytija_KTs,lead_Komment_k_prichine_KTs,lead_Prichina_zakrytija_OP,lead_Komment_k_prichine_OP,lead_Data_oplaty_1,lead_Data_oplaty_4,lead_Data_oplaty_5,lead_Data_oplaty_6,lead_Data_oplaty_7,lead_Data_oplaty_8,lead_Data_oplaty_9,lead_Data_oplaty_10,lead_Summa_oplaty_1,lead_Summa_oplaty_4,lead_Summa_oplaty_5,lead_Summa_oplaty_6,lead_Summa_oplaty_7,lead_Summa_oplaty_8,lead_Summa_oplaty_9,lead_Summa_oplaty_10,lead_Ostatok_k_oplate,lead_Data_plan_oplaty_1,lead_Data_plan_oplaty_2,lead_Summa_plan_oplaty_1,lead_Summa_plan_oplaty_2,lead_Tip_oplaty_3,lead_Tip_oplaty_4,lead_Tip_oplaty_5,lead_Tip_oplaty_6,lead_Tip_oplaty_7,lead_Tip_oplaty_8,lead_Tip_oplaty_9,lead_Tip_oplaty_10,lead_Data_oplaty_3,lead_Summa_oplaty_3,lead_Tip_oplaty_1,lead_Tip_oplaty_2,lead_Data_oplaty_2,lead_Summa_oplaty_2,lead_Data_oplaty_11,lead_Data_oplaty_12,lead_Data_oplaty_13,lead_Data_oplaty_14,lead_Data_oplaty_15,lead_Summa_oplaty_11,lead_Summa_oplaty_12,lead_Summa_oplaty_13,lead_Summa_oplaty_14,lead_Summa_oplaty_15,lead_Tip_oplaty_11,lead_Tip_oplaty_12,lead_Tip_oplaty_13,lead_Tip_oplaty_14,lead_Tip_oplaty_15,lead_Otvety_s_kvizoprosa,lead_Data_2oj_konsultatsii,lead_Dozakrytie,lead_Otvety_s_kviza,lead_Operator,lead_Prichina_obraschenija,lead_VCh,lead_NCh,lead_Psihotip,lead_Situatsionnyj_blok,lead_Problemnyj_blok,lead_Izvlekajuschij_blok,lead_Nomer_linii_MANGO_OFFICE,lead_ITOGO_OPLAChENO,lead_Data_pervichnogo_obraschenija,lead_Data_poseschenija_konsultatsii,lead_Data_okonchanija_lechenija,lead_Vid_oplaty_1,lead_Vid_oplaty_2,lead_Vid_oplaty_3,lead_Vid_oplaty_4,lead_Vid_oplaty_5,lead_Vid_oplaty_6,lead_Vid_oplaty_7,lead_Vid_oplaty_8,lead_Vid_oplaty_9,lead_Vid_oplaty_10,lead_Vid_oplaty_11,lead_Vid_oplaty_12,lead_Vid_oplaty_13,lead_Vid_oplaty_14,lead_Vid_oplaty_15,lead_Sposob_oplaty,lead_Source_phone,lead_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,lead_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,lead_TsOV_Identifikator_kontakta,lead_Data_smeny_kuratora,lead_ID_predyduschego_kuratora,klinika,contacts_1_id,contacts_1_name,contacts_1_responsible_user,contacts_1_contact_Dolzhnost,contacts_1_contact_Telefon,contacts_1_contact_Email,contacts_1_contact_Nomer_linii_MANGO_OFFICE,contacts_1_contact_Source_phone,contacts_1_contact_Whatsgroup_WZ,contacts_1_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kontakta,contacts_1_contact_Komment,contacts_1_companies_0_id,contacts_1_companies_0_name,contacts_1_companies_0_responsible_user,contacts_1_companies_0_company_Telefon,contacts_1_companies_0_company_Email,contacts_1_companies_0_company_Web,contacts_1_companies_0_company_Adres,contacts_0_contact_Instagram,contacts_0_contact_Instagram_WZ,contacts_0_contact_Profil,contacts_0_contact_Polzovatelskoe_soglashenie,contacts_0_contact_Kommentarij,contacts_0_companies_0_company_INN,contacts_0_companies_0_company_Sfera,contacts_0_companies_0_company_Oborot,contacts_0_companies_0_company_Kolichestvo_sotrudnikov,contacts_0_companies_0_company_Tip_programmy,companies_0_company_INN,companies_0_company_Sfera,companies_0_company_Oborot,companies_0_company_Kolichestvo_sotrudnikov,companies_0_company_Tip_programmy,lead_OSTATOK_K_OPLATE,lead_Sozdana_iz,lead_Obnovlena_iz,lead_Metrika_Jandeks,lead_Sotrudnik_otdela_servisa,lead_Klinika,lead_Data_prof_osmotra,lead_Kreditrassrochka,lead_Sotrudnik_vtorichnogo_otdela,lead_Problema,lead_Prichina_reshenija_konflikta_konflikta,lead_Data_oplaty_16,lead_Summa_oplaty_16,lead_Tip_oplaty_16,lead_Vid_oplaty_16,lead_Skoring_patsienta,lead_Skoring,lead_Data_oplaty_17,lead_Data_oplaty_18,lead_Data_oplaty_19,lead_Data_oplaty_20,lead_Summa_oplaty_17,lead_Summa_oplaty_18,lead_Summa_oplaty_19,lead_Summa_oplaty_20,lead_Tip_oplaty_17,lead_Tip_oplaty_18,lead_Tip_oplaty_19,lead_Tip_oplaty_20,lead_Vid_oplaty_17,lead_Vid_oplaty_18,lead_Vid_oplaty_19,lead_Vid_oplaty_20,lead_postbackurl,lead_Prichiny_konflikta,lead_Kommentarij,lead_Kategorija_patsienta,lead_Kvalifikatsija_KO,lead_UTM_SOURCE,lead_UTM_MEDIUM,lead_UTM_CAMPAIGN,lead_UTM_CONTENT,lead_UTM_TERM,lead_Summa_plan_oplaty_3,lead_Summa_plan_oplaty_4,lead_Summa_plan_oplaty_5,lead_Summa_plan_oplaty_6,lead_Data_plan_oplaty_3,lead_Data_plan_oplaty_4,lead_Data_plan_oplaty_5,lead_Data_plan_oplaty_6,lead_Data_oplaty_21,lead_Data_oplaty_22,lead_Data_oplaty_23,lead_Data_oplaty_24,lead_Data_oplaty_25,lead_Summa_oplaty_21,lead_Summa_oplaty_22,lead_Summa_oplaty_23,lead_Summa_oplaty_24,lead_Summa_oplaty_25,lead_Tip_oplaty_21,lead_Tip_oplaty_22,lead_Tip_oplaty_23,lead_Tip_oplaty_24,lead_Tip_oplaty_25,lead_Vid_oplaty_21,lead_Vid_oplaty_22,lead_Vid_oplaty_23,lead_Vid_oplaty_24,lead_Vid_oplaty_25,lead_TRANID,lead_FORMNAME,lead_FORMID,lead_REFERER,contacts_1_contact_Instagram,contacts_1_contact_Instagram_WZ,contacts_1_contact_Profil,contacts_1_contact_Polzovatelskoe_soglashenie,contacts_1_contact_Kommentarij,contacts_1_companies_0_company_INN,contacts_1_companies_0_company_Sfera,contacts_1_companies_0_company_Oborot,contacts_1_companies_0_company_Kolichestvo_sotrudnikov,contacts_1_companies_0_company_Tip_programmy,contacts_2_id,contacts_2_name,contacts_2_responsible_user,contacts_2_contact_Dolzhnost,contacts_2_contact_Telefon,contacts_2_contact_Email,contacts_2_contact_Nomer_linii_MANGO_OFFICE,contacts_2_contact_Instagram,contacts_2_contact_Instagram_WZ,contacts_2_contact_Profil,contacts_2_contact_Whatsgroup_WZ,contacts_2_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_2_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_2_contact_TsOV_Identifikator_kontakta,contacts_2_contact_Source_phone,contacts_2_contact_Polzovatelskoe_soglashenie,contacts_2_contact_Kommentarij,contacts_2_companies_0_id,contacts_2_companies_0_name,contacts_2_companies_0_responsible_user,contacts_2_companies_0_company_Telefon,contacts_2_companies_0_company_Email,contacts_2_companies_0_company_Web,contacts_2_companies_0_company_Adres,contacts_2_companies_0_company_INN,contacts_2_companies_0_company_Sfera,contacts_2_companies_0_company_Oborot,contacts_2_companies_0_company_Kolichestvo_sotrudnikov,contacts_2_companies_0_company_Tip_programmy)
        SELECT source.*
        FROM (
            SELECT id,name,price,responsible_user,created_at,created_by,updated_at,updated_by,closed_at,tags,pipeline,status_id,contacts_0_id,contacts_0_name,contacts_0_responsible_user,contacts_0_contact_Dolzhnost,contacts_0_contact_Telefon,contacts_0_contact_Email,contacts_0_contact_Nomer_linii_MANGO_OFFICE,contacts_0_contact_Source_phone,contacts_0_contact_Whatsgroup_WZ,contacts_0_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kontakta,contacts_0_contact_Komment,contacts_0_companies_0_id,contacts_0_companies_0_name,contacts_0_companies_0_responsible_user,contacts_0_companies_0_company_Telefon,contacts_0_companies_0_company_Email,contacts_0_companies_0_company_Web,contacts_0_companies_0_company_Adres,etap_sdelki,companies_0_id,companies_0_name,companies_0_responsible_user,companies_0_company_Telefon,companies_0_company_Email,companies_0_company_Web,companies_0_company_Adres,lead_utm_content,lead_utm_medium,lead_utm_campaign,lead_utm_source,lead_utm_term,lead_utm_referrer,lead_roistat,lead_referrer,lead_openstat_service,lead_openstat_campaign,lead_openstat_ad,lead_openstat_source,lead_from,lead_gclientid,lead__ym_uid,lead__ym_counter,lead_gclid,lead_yclid,lead_fbclid,lead_ID_sajta_v_Calltouch,lead_ID_zvonka_v_Calltouch,lead_ID_zajavki_v_Calltouch,lead_Istochnik_utm_source,lead_Kanal_utm_medium,lead_Kampanija_utm_campaign,lead_Objavlenie_utm_content,lead_Kljuchevoe_slovo_utm_term,lead_Jandeks_Metrika,lead_Otslezhivaemyj_sajt,lead_Data_Zapis,lead_Data_Javka,lead_Data_PTsP,lead_Data_nachalo_lechenija,lead_Kategorija_dlja_OP,lead_PervichkaVtorichka,lead_Tip_obraschenija,lead_Data_1oj_konsultatsii,lead_Konsdoktor_perv_doktor,lead_Tip_konsultatsii,lead_Prichina_zakrytija_KTs,lead_Komment_k_prichine_KTs,lead_Prichina_zakrytija_OP,lead_Komment_k_prichine_OP,lead_Data_oplaty_1,lead_Data_oplaty_4,lead_Data_oplaty_5,lead_Data_oplaty_6,lead_Data_oplaty_7,lead_Data_oplaty_8,lead_Data_oplaty_9,lead_Data_oplaty_10,lead_Summa_oplaty_1,lead_Summa_oplaty_4,lead_Summa_oplaty_5,lead_Summa_oplaty_6,lead_Summa_oplaty_7,lead_Summa_oplaty_8,lead_Summa_oplaty_9,lead_Summa_oplaty_10,lead_Ostatok_k_oplate,lead_Data_plan_oplaty_1,lead_Data_plan_oplaty_2,lead_Summa_plan_oplaty_1,lead_Summa_plan_oplaty_2,lead_Tip_oplaty_3,lead_Tip_oplaty_4,lead_Tip_oplaty_5,lead_Tip_oplaty_6,lead_Tip_oplaty_7,lead_Tip_oplaty_8,lead_Tip_oplaty_9,lead_Tip_oplaty_10,lead_Data_oplaty_3,lead_Summa_oplaty_3,lead_Tip_oplaty_1,lead_Tip_oplaty_2,lead_Data_oplaty_2,lead_Summa_oplaty_2,lead_Data_oplaty_11,lead_Data_oplaty_12,lead_Data_oplaty_13,lead_Data_oplaty_14,lead_Data_oplaty_15,lead_Summa_oplaty_11,lead_Summa_oplaty_12,lead_Summa_oplaty_13,lead_Summa_oplaty_14,lead_Summa_oplaty_15,lead_Tip_oplaty_11,lead_Tip_oplaty_12,lead_Tip_oplaty_13,lead_Tip_oplaty_14,lead_Tip_oplaty_15,lead_Otvety_s_kvizoprosa,lead_Data_2oj_konsultatsii,lead_Dozakrytie,lead_Otvety_s_kviza,lead_Operator,lead_Prichina_obraschenija,lead_VCh,lead_NCh,lead_Psihotip,lead_Situatsionnyj_blok,lead_Problemnyj_blok,lead_Izvlekajuschij_blok,lead_Nomer_linii_MANGO_OFFICE,lead_ITOGO_OPLAChENO,lead_Data_pervichnogo_obraschenija,lead_Data_poseschenija_konsultatsii,lead_Data_okonchanija_lechenija,lead_Vid_oplaty_1,lead_Vid_oplaty_2,lead_Vid_oplaty_3,lead_Vid_oplaty_4,lead_Vid_oplaty_5,lead_Vid_oplaty_6,lead_Vid_oplaty_7,lead_Vid_oplaty_8,lead_Vid_oplaty_9,lead_Vid_oplaty_10,lead_Vid_oplaty_11,lead_Vid_oplaty_12,lead_Vid_oplaty_13,lead_Vid_oplaty_14,lead_Vid_oplaty_15,lead_Sposob_oplaty,lead_Source_phone,lead_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,lead_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,lead_TsOV_Identifikator_kontakta,lead_Data_smeny_kuratora,lead_ID_predyduschego_kuratora,klinika,contacts_1_id,contacts_1_name,contacts_1_responsible_user,contacts_1_contact_Dolzhnost,contacts_1_contact_Telefon,contacts_1_contact_Email,contacts_1_contact_Nomer_linii_MANGO_OFFICE,contacts_1_contact_Source_phone,contacts_1_contact_Whatsgroup_WZ,contacts_1_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kontakta,contacts_1_contact_Komment,contacts_1_companies_0_id,contacts_1_companies_0_name,contacts_1_companies_0_responsible_user,contacts_1_companies_0_company_Telefon,contacts_1_companies_0_company_Email,contacts_1_companies_0_company_Web,contacts_1_companies_0_company_Adres,NULL AS contacts_0_contact_Instagram,NULL AS contacts_0_contact_Instagram_WZ,NULL AS contacts_0_contact_Profil,NULL AS contacts_0_contact_Polzovatelskoe_soglashenie,NULL AS contacts_0_contact_Kommentarij,NULL AS contacts_0_companies_0_company_INN,NULL AS contacts_0_companies_0_company_Sfera,NULL AS contacts_0_companies_0_company_Oborot,NULL AS contacts_0_companies_0_company_Kolichestvo_sotrudnikov,NULL AS contacts_0_companies_0_company_Tip_programmy,NULL AS companies_0_company_INN,NULL AS companies_0_company_Sfera,NULL AS companies_0_company_Oborot,NULL AS companies_0_company_Kolichestvo_sotrudnikov,NULL AS companies_0_company_Tip_programmy,NULL AS lead_OSTATOK_K_OPLATE,NULL AS lead_Sozdana_iz,NULL AS lead_Obnovlena_iz,NULL AS lead_Metrika_Jandeks,NULL AS lead_Sotrudnik_otdela_servisa,NULL AS lead_Klinika,NULL AS lead_Data_prof_osmotra,NULL AS lead_Kreditrassrochka,NULL AS lead_Sotrudnik_vtorichnogo_otdela,NULL AS lead_Problema,NULL AS lead_Prichina_reshenija_konflikta_konflikta,NULL AS lead_Data_oplaty_16,NULL AS lead_Summa_oplaty_16,NULL AS lead_Tip_oplaty_16,NULL AS lead_Vid_oplaty_16,NULL AS lead_Skoring_patsienta,NULL AS lead_Skoring,NULL AS lead_Data_oplaty_17,NULL AS lead_Data_oplaty_18,NULL AS lead_Data_oplaty_19,NULL AS lead_Data_oplaty_20,NULL AS lead_Summa_oplaty_17,NULL AS lead_Summa_oplaty_18,NULL AS lead_Summa_oplaty_19,NULL AS lead_Summa_oplaty_20,NULL AS lead_Tip_oplaty_17,NULL AS lead_Tip_oplaty_18,NULL AS lead_Tip_oplaty_19,NULL AS lead_Tip_oplaty_20,NULL AS lead_Vid_oplaty_17,NULL AS lead_Vid_oplaty_18,NULL AS lead_Vid_oplaty_19,NULL AS lead_Vid_oplaty_20,NULL AS lead_postbackurl,NULL AS lead_Prichiny_konflikta,NULL AS lead_Kommentarij,NULL AS lead_Kategorija_patsienta,NULL AS lead_Kvalifikatsija_KO,NULL AS lead_UTM_SOURCE,NULL AS lead_UTM_MEDIUM,NULL AS lead_UTM_CAMPAIGN,NULL AS lead_UTM_CONTENT,NULL AS lead_UTM_TERM,NULL AS lead_Summa_plan_oplaty_3,NULL AS lead_Summa_plan_oplaty_4,NULL AS lead_Summa_plan_oplaty_5,NULL AS lead_Summa_plan_oplaty_6,NULL AS lead_Data_plan_oplaty_3,NULL AS lead_Data_plan_oplaty_4,NULL AS lead_Data_plan_oplaty_5,NULL AS lead_Data_plan_oplaty_6,NULL AS lead_Data_oplaty_21,NULL AS lead_Data_oplaty_22,NULL AS lead_Data_oplaty_23,NULL AS lead_Data_oplaty_24,NULL AS lead_Data_oplaty_25,NULL AS lead_Summa_oplaty_21,NULL AS lead_Summa_oplaty_22,NULL AS lead_Summa_oplaty_23,NULL AS lead_Summa_oplaty_24,NULL AS lead_Summa_oplaty_25,NULL AS lead_Tip_oplaty_21,NULL AS lead_Tip_oplaty_22,NULL AS lead_Tip_oplaty_23,NULL AS lead_Tip_oplaty_24,NULL AS lead_Tip_oplaty_25,NULL AS lead_Vid_oplaty_21,NULL AS lead_Vid_oplaty_22,NULL AS lead_Vid_oplaty_23,NULL AS lead_Vid_oplaty_24,NULL AS lead_Vid_oplaty_25,NULL AS lead_TRANID,NULL AS lead_FORMNAME,NULL AS lead_FORMID,NULL AS lead_REFERER,NULL AS contacts_1_contact_Instagram,NULL AS contacts_1_contact_Instagram_WZ,NULL AS contacts_1_contact_Profil,NULL AS contacts_1_contact_Polzovatelskoe_soglashenie,NULL AS contacts_1_contact_Kommentarij,NULL AS contacts_1_companies_0_company_INN,NULL AS contacts_1_companies_0_company_Sfera,NULL AS contacts_1_companies_0_company_Oborot,NULL AS contacts_1_companies_0_company_Kolichestvo_sotrudnikov,NULL AS contacts_1_companies_0_company_Tip_programmy,NULL AS contacts_2_id,NULL AS contacts_2_name,NULL AS contacts_2_responsible_user,NULL AS contacts_2_contact_Dolzhnost,NULL AS contacts_2_contact_Telefon,NULL AS contacts_2_contact_Email,NULL AS contacts_2_contact_Nomer_linii_MANGO_OFFICE,NULL AS contacts_2_contact_Instagram,NULL AS contacts_2_contact_Instagram_WZ,NULL AS contacts_2_contact_Profil,NULL AS contacts_2_contact_Whatsgroup_WZ,NULL AS contacts_2_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,NULL AS contacts_2_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,NULL AS contacts_2_contact_TsOV_Identifikator_kontakta,NULL AS contacts_2_contact_Source_phone,NULL AS contacts_2_contact_Polzovatelskoe_soglashenie,NULL AS contacts_2_contact_Kommentarij,NULL AS contacts_2_companies_0_id,NULL AS contacts_2_companies_0_name,NULL AS contacts_2_companies_0_responsible_user,NULL AS contacts_2_companies_0_company_Telefon,NULL AS contacts_2_companies_0_company_Email,NULL AS contacts_2_companies_0_company_Web,NULL AS contacts_2_companies_0_company_Adres,NULL AS contacts_2_companies_0_company_INN,NULL AS contacts_2_companies_0_company_Sfera,NULL AS contacts_2_companies_0_company_Oborot,NULL AS contacts_2_companies_0_company_Kolichestvo_sotrudnikov,NULL AS contacts_2_companies_0_company_Tip_programmy FROM {db_name}.msc
            UNION ALL
            SELECT id,name,price,responsible_user,created_at,created_by,updated_at,updated_by,closed_at,tags,pipeline,status_id,contacts_0_id,contacts_0_name,contacts_0_responsible_user,contacts_0_contact_Dolzhnost,contacts_0_contact_Telefon,contacts_0_contact_Email,contacts_0_contact_Nomer_linii_MANGO_OFFICE,contacts_0_contact_Source_phone,contacts_0_contact_Whatsgroup_WZ,contacts_0_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kontakta,NULL AS contacts_0_contact_Komment,contacts_0_companies_0_id,contacts_0_companies_0_name,contacts_0_companies_0_responsible_user,contacts_0_companies_0_company_Telefon,contacts_0_companies_0_company_Email,contacts_0_companies_0_company_Web,contacts_0_companies_0_company_Adres,etap_sdelki,companies_0_id,companies_0_name,companies_0_responsible_user,companies_0_company_Telefon,companies_0_company_Email,companies_0_company_Web,companies_0_company_Adres,lead_utm_content,lead_utm_medium,lead_utm_campaign,lead_utm_source,lead_utm_term,lead_utm_referrer,lead_roistat,lead_referrer,lead_openstat_service,lead_openstat_campaign,lead_openstat_ad,lead_openstat_source,lead_from,lead_gclientid,lead__ym_uid,lead__ym_counter,lead_gclid,lead_yclid,lead_fbclid,lead_ID_sajta_v_Calltouch,lead_ID_zvonka_v_Calltouch,lead_ID_zajavki_v_Calltouch,lead_Istochnik_utm_source,lead_Kanal_utm_medium,lead_Kampanija_utm_campaign,lead_Objavlenie_utm_content,lead_Kljuchevoe_slovo_utm_term,NULL AS lead_Jandeks_Metrika,lead_Otslezhivaemyj_sajt,lead_Data_Zapis,lead_Data_Javka,lead_Data_PTsP,lead_Data_nachalo_lechenija,lead_Kategorija_dlja_OP,lead_PervichkaVtorichka,lead_Tip_obraschenija,lead_Data_1oj_konsultatsii,lead_Konsdoktor_perv_doktor,lead_Tip_konsultatsii,lead_Prichina_zakrytija_KTs,lead_Komment_k_prichine_KTs,lead_Prichina_zakrytija_OP,lead_Komment_k_prichine_OP,lead_Data_oplaty_1,lead_Data_oplaty_4,lead_Data_oplaty_5,lead_Data_oplaty_6,lead_Data_oplaty_7,lead_Data_oplaty_8,lead_Data_oplaty_9,lead_Data_oplaty_10,lead_Summa_oplaty_1,lead_Summa_oplaty_4,lead_Summa_oplaty_5,lead_Summa_oplaty_6,lead_Summa_oplaty_7,lead_Summa_oplaty_8,lead_Summa_oplaty_9,lead_Summa_oplaty_10,NULL AS lead_Ostatok_k_oplate,lead_Data_plan_oplaty_1,lead_Data_plan_oplaty_2,lead_Summa_plan_oplaty_1,lead_Summa_plan_oplaty_2,lead_Tip_oplaty_3,lead_Tip_oplaty_4,lead_Tip_oplaty_5,lead_Tip_oplaty_6,lead_Tip_oplaty_7,lead_Tip_oplaty_8,lead_Tip_oplaty_9,lead_Tip_oplaty_10,lead_Data_oplaty_3,lead_Summa_oplaty_3,lead_Tip_oplaty_1,lead_Tip_oplaty_2,lead_Data_oplaty_2,lead_Summa_oplaty_2,lead_Data_oplaty_11,lead_Data_oplaty_12,lead_Data_oplaty_13,lead_Data_oplaty_14,lead_Data_oplaty_15,lead_Summa_oplaty_11,lead_Summa_oplaty_12,lead_Summa_oplaty_13,lead_Summa_oplaty_14,lead_Summa_oplaty_15,lead_Tip_oplaty_11,lead_Tip_oplaty_12,lead_Tip_oplaty_13,lead_Tip_oplaty_14,lead_Tip_oplaty_15,lead_Otvety_s_kvizoprosa,lead_Data_2oj_konsultatsii,lead_Dozakrytie,lead_Otvety_s_kviza,lead_Operator,lead_Prichina_obraschenija,NULL AS lead_VCh,NULL AS lead_NCh,lead_Psihotip,lead_Situatsionnyj_blok,lead_Problemnyj_blok,lead_Izvlekajuschij_blok,lead_Nomer_linii_MANGO_OFFICE,NULL AS lead_ITOGO_OPLAChENO,lead_Data_pervichnogo_obraschenija,lead_Data_poseschenija_konsultatsii,lead_Data_okonchanija_lechenija,lead_Vid_oplaty_1,lead_Vid_oplaty_2,lead_Vid_oplaty_3,lead_Vid_oplaty_4,lead_Vid_oplaty_5,lead_Vid_oplaty_6,lead_Vid_oplaty_7,lead_Vid_oplaty_8,lead_Vid_oplaty_9,lead_Vid_oplaty_10,lead_Vid_oplaty_11,lead_Vid_oplaty_12,lead_Vid_oplaty_13,lead_Vid_oplaty_14,lead_Vid_oplaty_15,NULL AS lead_Sposob_oplaty,lead_Source_phone,lead_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,lead_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,lead_TsOV_Identifikator_kontakta,lead_Data_smeny_kuratora,lead_ID_predyduschego_kuratora,NULL AS klinika,contacts_1_id,contacts_1_name,contacts_1_responsible_user,contacts_1_contact_Dolzhnost,contacts_1_contact_Telefon,contacts_1_contact_Email,contacts_1_contact_Nomer_linii_MANGO_OFFICE,contacts_1_contact_Source_phone,contacts_1_contact_Whatsgroup_WZ,contacts_1_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kontakta,NULL AS contacts_1_contact_Komment,contacts_1_companies_0_id,contacts_1_companies_0_name,contacts_1_companies_0_responsible_user,contacts_1_companies_0_company_Telefon,contacts_1_companies_0_company_Email,contacts_1_companies_0_company_Web,contacts_1_companies_0_company_Adres,contacts_0_contact_Instagram,contacts_0_contact_Instagram_WZ,contacts_0_contact_Profil,contacts_0_contact_Polzovatelskoe_soglashenie,contacts_0_contact_Kommentarij,contacts_0_companies_0_company_INN,contacts_0_companies_0_company_Sfera,contacts_0_companies_0_company_Oborot,contacts_0_companies_0_company_Kolichestvo_sotrudnikov,contacts_0_companies_0_company_Tip_programmy,companies_0_company_INN,companies_0_company_Sfera,companies_0_company_Oborot,companies_0_company_Kolichestvo_sotrudnikov,companies_0_company_Tip_programmy,lead_OSTATOK_K_OPLATE,lead_Sozdana_iz,lead_Obnovlena_iz,lead_Metrika_Jandeks,lead_Sotrudnik_otdela_servisa,lead_Klinika,lead_Data_prof_osmotra,lead_Kreditrassrochka,lead_Sotrudnik_vtorichnogo_otdela,lead_Problema,lead_Prichina_reshenija_konflikta_konflikta,lead_Data_oplaty_16,lead_Summa_oplaty_16,lead_Tip_oplaty_16,lead_Vid_oplaty_16,lead_Skoring_patsienta,lead_Skoring,lead_Data_oplaty_17,lead_Data_oplaty_18,lead_Data_oplaty_19,lead_Data_oplaty_20,lead_Summa_oplaty_17,lead_Summa_oplaty_18,lead_Summa_oplaty_19,lead_Summa_oplaty_20,lead_Tip_oplaty_17,lead_Tip_oplaty_18,lead_Tip_oplaty_19,lead_Tip_oplaty_20,lead_Vid_oplaty_17,lead_Vid_oplaty_18,lead_Vid_oplaty_19,lead_Vid_oplaty_20,lead_postbackurl,lead_Prichiny_konflikta,lead_Kommentarij,lead_Kategorija_patsienta,lead_Kvalifikatsija_KO,lead_UTM_SOURCE,lead_UTM_MEDIUM,lead_UTM_CAMPAIGN,lead_UTM_CONTENT,lead_UTM_TERM,lead_Summa_plan_oplaty_3,lead_Summa_plan_oplaty_4,lead_Summa_plan_oplaty_5,lead_Summa_plan_oplaty_6,lead_Data_plan_oplaty_3,lead_Data_plan_oplaty_4,lead_Data_plan_oplaty_5,lead_Data_plan_oplaty_6,lead_Data_oplaty_21,lead_Data_oplaty_22,lead_Data_oplaty_23,lead_Data_oplaty_24,lead_Data_oplaty_25,lead_Summa_oplaty_21,lead_Summa_oplaty_22,lead_Summa_oplaty_23,lead_Summa_oplaty_24,lead_Summa_oplaty_25,lead_Tip_oplaty_21,lead_Tip_oplaty_22,lead_Tip_oplaty_23,lead_Tip_oplaty_24,lead_Tip_oplaty_25,lead_Vid_oplaty_21,lead_Vid_oplaty_22,lead_Vid_oplaty_23,lead_Vid_oplaty_24,lead_Vid_oplaty_25,lead_TRANID,lead_FORMNAME,lead_FORMID,lead_REFERER,contacts_1_contact_Instagram,contacts_1_contact_Instagram_WZ,contacts_1_contact_Profil,contacts_1_contact_Polzovatelskoe_soglashenie,contacts_1_contact_Kommentarij,contacts_1_companies_0_company_INN,contacts_1_companies_0_company_Sfera,contacts_1_companies_0_company_Oborot,contacts_1_companies_0_company_Kolichestvo_sotrudnikov,contacts_1_companies_0_company_Tip_programmy,contacts_2_id,contacts_2_name,contacts_2_responsible_user,contacts_2_contact_Dolzhnost,contacts_2_contact_Telefon,contacts_2_contact_Email,contacts_2_contact_Nomer_linii_MANGO_OFFICE,contacts_2_contact_Instagram,contacts_2_contact_Instagram_WZ,contacts_2_contact_Profil,contacts_2_contact_Whatsgroup_WZ,contacts_2_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_2_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_2_contact_TsOV_Identifikator_kontakta,contacts_2_contact_Source_phone,contacts_2_contact_Polzovatelskoe_soglashenie,contacts_2_contact_Kommentarij,contacts_2_companies_0_id,contacts_2_companies_0_name,contacts_2_companies_0_responsible_user,contacts_2_companies_0_company_Telefon,contacts_2_companies_0_company_Email,contacts_2_companies_0_company_Web,contacts_2_companies_0_company_Adres,contacts_2_companies_0_company_INN,contacts_2_companies_0_company_Sfera,contacts_2_companies_0_company_Oborot,contacts_2_companies_0_company_Kolichestvo_sotrudnikov,contacts_2_companies_0_company_Tip_programmy FROM {db_name}.spb
        ) AS source;
        """
        client.command(insert_query)
    else:
        create_combined_query = f"""
        CREATE TABLE {combined_table}
        ENGINE=MergeTree()
        ORDER BY coalesce(id, 0)
        AS
        SELECT id,name,price,responsible_user,created_at,created_by,updated_at,updated_by,closed_at,tags,pipeline,status_id,contacts_0_id,contacts_0_name,contacts_0_responsible_user,contacts_0_contact_Dolzhnost,contacts_0_contact_Telefon,contacts_0_contact_Email,contacts_0_contact_Nomer_linii_MANGO_OFFICE,contacts_0_contact_Source_phone,contacts_0_contact_Whatsgroup_WZ,contacts_0_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kontakta,contacts_0_contact_Komment,contacts_0_companies_0_id,contacts_0_companies_0_name,contacts_0_companies_0_responsible_user,contacts_0_companies_0_company_Telefon,contacts_0_companies_0_company_Email,contacts_0_companies_0_company_Web,contacts_0_companies_0_company_Adres,etap_sdelki,companies_0_id,companies_0_name,companies_0_responsible_user,companies_0_company_Telefon,companies_0_company_Email,companies_0_company_Web,companies_0_company_Adres,lead_utm_content,lead_utm_medium,lead_utm_campaign,lead_utm_source,lead_utm_term,lead_utm_referrer,lead_roistat,lead_referrer,lead_openstat_service,lead_openstat_campaign,lead_openstat_ad,lead_openstat_source,lead_from,lead_gclientid,lead__ym_uid,lead__ym_counter,lead_gclid,lead_yclid,lead_fbclid,lead_ID_sajta_v_Calltouch,lead_ID_zvonka_v_Calltouch,lead_ID_zajavki_v_Calltouch,lead_Istochnik_utm_source,lead_Kanal_utm_medium,lead_Kampanija_utm_campaign,lead_Objavlenie_utm_content,lead_Kljuchevoe_slovo_utm_term,lead_Jandeks_Metrika,lead_Otslezhivaemyj_sajt,lead_Data_Zapis,lead_Data_Javka,lead_Data_PTsP,lead_Data_nachalo_lechenija,lead_Kategorija_dlja_OP,lead_PervichkaVtorichka,lead_Tip_obraschenija,lead_Data_1oj_konsultatsii,lead_Konsdoktor_perv_doktor,lead_Tip_konsultatsii,lead_Prichina_zakrytija_KTs,lead_Komment_k_prichine_KTs,lead_Prichina_zakrytija_OP,lead_Komment_k_prichine_OP,lead_Data_oplaty_1,lead_Data_oplaty_4,lead_Data_oplaty_5,lead_Data_oplaty_6,lead_Data_oplaty_7,lead_Data_oplaty_8,lead_Data_oplaty_9,lead_Data_oplaty_10,lead_Summa_oplaty_1,lead_Summa_oplaty_4,lead_Summa_oplaty_5,lead_Summa_oplaty_6,lead_Summa_oplaty_7,lead_Summa_oplaty_8,lead_Summa_oplaty_9,lead_Summa_oplaty_10,lead_Ostatok_k_oplate,lead_Data_plan_oplaty_1,lead_Data_plan_oplaty_2,lead_Summa_plan_oplaty_1,lead_Summa_plan_oplaty_2,lead_Tip_oplaty_3,lead_Tip_oplaty_4,lead_Tip_oplaty_5,lead_Tip_oplaty_6,lead_Tip_oplaty_7,lead_Tip_oplaty_8,lead_Tip_oplaty_9,lead_Tip_oplaty_10,lead_Data_oplaty_3,lead_Summa_oplaty_3,lead_Tip_oplaty_1,lead_Tip_oplaty_2,lead_Data_oplaty_2,lead_Summa_oplaty_2,lead_Data_oplaty_11,lead_Data_oplaty_12,lead_Data_oplaty_13,lead_Data_oplaty_14,lead_Data_oplaty_15,lead_Summa_oplaty_11,lead_Summa_oplaty_12,lead_Summa_oplaty_13,lead_Summa_oplaty_14,lead_Summa_oplaty_15,lead_Tip_oplaty_11,lead_Tip_oplaty_12,lead_Tip_oplaty_13,lead_Tip_oplaty_14,lead_Tip_oplaty_15,lead_Otvety_s_kvizoprosa,lead_Data_2oj_konsultatsii,lead_Dozakrytie,lead_Otvety_s_kviza,lead_Operator,lead_Prichina_obraschenija,lead_VCh,lead_NCh,lead_Psihotip,lead_Situatsionnyj_blok,lead_Problemnyj_blok,lead_Izvlekajuschij_blok,lead_Nomer_linii_MANGO_OFFICE,lead_ITOGO_OPLAChENO,lead_Data_pervichnogo_obraschenija,lead_Data_poseschenija_konsultatsii,lead_Data_okonchanija_lechenija,lead_Vid_oplaty_1,lead_Vid_oplaty_2,lead_Vid_oplaty_3,lead_Vid_oplaty_4,lead_Vid_oplaty_5,lead_Vid_oplaty_6,lead_Vid_oplaty_7,lead_Vid_oplaty_8,lead_Vid_oplaty_9,lead_Vid_oplaty_10,lead_Vid_oplaty_11,lead_Vid_oplaty_12,lead_Vid_oplaty_13,lead_Vid_oplaty_14,lead_Vid_oplaty_15,lead_Sposob_oplaty,lead_Source_phone,lead_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,lead_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,lead_TsOV_Identifikator_kontakta,lead_Data_smeny_kuratora,lead_ID_predyduschego_kuratora,klinika,contacts_1_id,contacts_1_name,contacts_1_responsible_user,contacts_1_contact_Dolzhnost,contacts_1_contact_Telefon,contacts_1_contact_Email,contacts_1_contact_Nomer_linii_MANGO_OFFICE,contacts_1_contact_Source_phone,contacts_1_contact_Whatsgroup_WZ,contacts_1_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kontakta,contacts_1_contact_Komment,contacts_1_companies_0_id,contacts_1_companies_0_name,contacts_1_companies_0_responsible_user,contacts_1_companies_0_company_Telefon,contacts_1_companies_0_company_Email,contacts_1_companies_0_company_Web,contacts_1_companies_0_company_Adres,NULL AS contacts_0_contact_Instagram,NULL AS contacts_0_contact_Instagram_WZ,NULL AS contacts_0_contact_Profil,NULL AS contacts_0_contact_Polzovatelskoe_soglashenie,NULL AS contacts_0_contact_Kommentarij,NULL AS contacts_0_companies_0_company_INN,NULL AS contacts_0_companies_0_company_Sfera,NULL AS contacts_0_companies_0_company_Oborot,NULL AS contacts_0_companies_0_company_Kolichestvo_sotrudnikov,NULL AS contacts_0_companies_0_company_Tip_programmy,NULL AS companies_0_company_INN,NULL AS companies_0_company_Sfera,NULL AS companies_0_company_Oborot,NULL AS companies_0_company_Kolichestvo_sotrudnikov,NULL AS companies_0_company_Tip_programmy,NULL AS lead_OSTATOK_K_OPLATE,NULL AS lead_Sozdana_iz,NULL AS lead_Obnovlena_iz,NULL AS lead_Metrika_Jandeks,NULL AS lead_Sotrudnik_otdela_servisa,NULL AS lead_Klinika,NULL AS lead_Data_prof_osmotra,NULL AS lead_Kreditrassrochka,NULL AS lead_Sotrudnik_vtorichnogo_otdela,NULL AS lead_Problema,NULL AS lead_Prichina_reshenija_konflikta_konflikta,NULL AS lead_Data_oplaty_16,NULL AS lead_Summa_oplaty_16,NULL AS lead_Tip_oplaty_16,NULL AS lead_Vid_oplaty_16,NULL AS lead_Skoring_patsienta,NULL AS lead_Skoring,NULL AS lead_Data_oplaty_17,NULL AS lead_Data_oplaty_18,NULL AS lead_Data_oplaty_19,NULL AS lead_Data_oplaty_20,NULL AS lead_Summa_oplaty_17,NULL AS lead_Summa_oplaty_18,NULL AS lead_Summa_oplaty_19,NULL AS lead_Summa_oplaty_20,NULL AS lead_Tip_oplaty_17,NULL AS lead_Tip_oplaty_18,NULL AS lead_Tip_oplaty_19,NULL AS lead_Tip_oplaty_20,NULL AS lead_Vid_oplaty_17,NULL AS lead_Vid_oplaty_18,NULL AS lead_Vid_oplaty_19,NULL AS lead_Vid_oplaty_20,NULL AS lead_postbackurl,NULL AS lead_Prichiny_konflikta,NULL AS lead_Kommentarij,NULL AS lead_Kategorija_patsienta,NULL AS lead_Kvalifikatsija_KO,NULL AS lead_UTM_SOURCE,NULL AS lead_UTM_MEDIUM,NULL AS lead_UTM_CAMPAIGN,NULL AS lead_UTM_CONTENT,NULL AS lead_UTM_TERM,NULL AS lead_Summa_plan_oplaty_3,NULL AS lead_Summa_plan_oplaty_4,NULL AS lead_Summa_plan_oplaty_5,NULL AS lead_Summa_plan_oplaty_6,NULL AS lead_Data_plan_oplaty_3,NULL AS lead_Data_plan_oplaty_4,NULL AS lead_Data_plan_oplaty_5,NULL AS lead_Data_plan_oplaty_6,NULL AS lead_Data_oplaty_21,NULL AS lead_Data_oplaty_22,NULL AS lead_Data_oplaty_23,NULL AS lead_Data_oplaty_24,NULL AS lead_Data_oplaty_25,NULL AS lead_Summa_oplaty_21,NULL AS lead_Summa_oplaty_22,NULL AS lead_Summa_oplaty_23,NULL AS lead_Summa_oplaty_24,NULL AS lead_Summa_oplaty_25,NULL AS lead_Tip_oplaty_21,NULL AS lead_Tip_oplaty_22,NULL AS lead_Tip_oplaty_23,NULL AS lead_Tip_oplaty_24,NULL AS lead_Tip_oplaty_25,NULL AS lead_Vid_oplaty_21,NULL AS lead_Vid_oplaty_22,NULL AS lead_Vid_oplaty_23,NULL AS lead_Vid_oplaty_24,NULL AS lead_Vid_oplaty_25,NULL AS lead_TRANID,NULL AS lead_FORMNAME,NULL AS lead_FORMID,NULL AS lead_REFERER,NULL AS contacts_1_contact_Instagram,NULL AS contacts_1_contact_Instagram_WZ,NULL AS contacts_1_contact_Profil,NULL AS contacts_1_contact_Polzovatelskoe_soglashenie,NULL AS contacts_1_contact_Kommentarij,NULL AS contacts_1_companies_0_company_INN,NULL AS contacts_1_companies_0_company_Sfera,NULL AS contacts_1_companies_0_company_Oborot,NULL AS contacts_1_companies_0_company_Kolichestvo_sotrudnikov,NULL AS contacts_1_companies_0_company_Tip_programmy,NULL AS contacts_2_id,NULL AS contacts_2_name,NULL AS contacts_2_responsible_user,NULL AS contacts_2_contact_Dolzhnost,NULL AS contacts_2_contact_Telefon,NULL AS contacts_2_contact_Email,NULL AS contacts_2_contact_Nomer_linii_MANGO_OFFICE,NULL AS contacts_2_contact_Instagram,NULL AS contacts_2_contact_Instagram_WZ,NULL AS contacts_2_contact_Profil,NULL AS contacts_2_contact_Whatsgroup_WZ,NULL AS contacts_2_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,NULL AS contacts_2_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,NULL AS contacts_2_contact_TsOV_Identifikator_kontakta,NULL AS contacts_2_contact_Source_phone,NULL AS contacts_2_contact_Polzovatelskoe_soglashenie,NULL AS contacts_2_contact_Kommentarij,NULL AS contacts_2_companies_0_id,NULL AS contacts_2_companies_0_name,NULL AS contacts_2_companies_0_responsible_user,NULL AS contacts_2_companies_0_company_Telefon,NULL AS contacts_2_companies_0_company_Email,NULL AS contacts_2_companies_0_company_Web,NULL AS contacts_2_companies_0_company_Adres,NULL AS contacts_2_companies_0_company_INN,NULL AS contacts_2_companies_0_company_Sfera,NULL AS contacts_2_companies_0_company_Oborot,NULL AS contacts_2_companies_0_company_Kolichestvo_sotrudnikov,NULL AS contacts_2_companies_0_company_Tip_programmy FROM {db_name}.msc
        UNION ALL
        SELECT id,name,price,responsible_user,created_at,created_by,updated_at,updated_by,closed_at,tags,pipeline,status_id,contacts_0_id,contacts_0_name,contacts_0_responsible_user,contacts_0_contact_Dolzhnost,contacts_0_contact_Telefon,contacts_0_contact_Email,contacts_0_contact_Nomer_linii_MANGO_OFFICE,contacts_0_contact_Source_phone,contacts_0_contact_Whatsgroup_WZ,contacts_0_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_0_contact_TsOV_Identifikator_kontakta,NULL AS contacts_0_contact_Komment,contacts_0_companies_0_id,contacts_0_companies_0_name,contacts_0_companies_0_responsible_user,contacts_0_companies_0_company_Telefon,contacts_0_companies_0_company_Email,contacts_0_companies_0_company_Web,contacts_0_companies_0_company_Adres,etap_sdelki,companies_0_id,companies_0_name,companies_0_responsible_user,companies_0_company_Telefon,companies_0_company_Email,companies_0_company_Web,companies_0_company_Adres,lead_utm_content,lead_utm_medium,lead_utm_campaign,lead_utm_source,lead_utm_term,lead_utm_referrer,lead_roistat,lead_referrer,lead_openstat_service,lead_openstat_campaign,lead_openstat_ad,lead_openstat_source,lead_from,lead_gclientid,lead__ym_uid,lead__ym_counter,lead_gclid,lead_yclid,lead_fbclid,lead_ID_sajta_v_Calltouch,lead_ID_zvonka_v_Calltouch,lead_ID_zajavki_v_Calltouch,lead_Istochnik_utm_source,lead_Kanal_utm_medium,lead_Kampanija_utm_campaign,lead_Objavlenie_utm_content,lead_Kljuchevoe_slovo_utm_term,NULL AS lead_Jandeks_Metrika,lead_Otslezhivaemyj_sajt,lead_Data_Zapis,lead_Data_Javka,lead_Data_PTsP,lead_Data_nachalo_lechenija,lead_Kategorija_dlja_OP,lead_PervichkaVtorichka,lead_Tip_obraschenija,lead_Data_1oj_konsultatsii,lead_Konsdoktor_perv_doktor,lead_Tip_konsultatsii,lead_Prichina_zakrytija_KTs,lead_Komment_k_prichine_KTs,lead_Prichina_zakrytija_OP,lead_Komment_k_prichine_OP,lead_Data_oplaty_1,lead_Data_oplaty_4,lead_Data_oplaty_5,lead_Data_oplaty_6,lead_Data_oplaty_7,lead_Data_oplaty_8,lead_Data_oplaty_9,lead_Data_oplaty_10,lead_Summa_oplaty_1,lead_Summa_oplaty_4,lead_Summa_oplaty_5,lead_Summa_oplaty_6,lead_Summa_oplaty_7,lead_Summa_oplaty_8,lead_Summa_oplaty_9,lead_Summa_oplaty_10,NULL AS lead_Ostatok_k_oplate,lead_Data_plan_oplaty_1,lead_Data_plan_oplaty_2,lead_Summa_plan_oplaty_1,lead_Summa_plan_oplaty_2,lead_Tip_oplaty_3,lead_Tip_oplaty_4,lead_Tip_oplaty_5,lead_Tip_oplaty_6,lead_Tip_oplaty_7,lead_Tip_oplaty_8,lead_Tip_oplaty_9,lead_Tip_oplaty_10,lead_Data_oplaty_3,lead_Summa_oplaty_3,lead_Tip_oplaty_1,lead_Tip_oplaty_2,lead_Data_oplaty_2,lead_Summa_oplaty_2,lead_Data_oplaty_11,lead_Data_oplaty_12,lead_Data_oplaty_13,lead_Data_oplaty_14,lead_Data_oplaty_15,lead_Summa_oplaty_11,lead_Summa_oplaty_12,lead_Summa_oplaty_13,lead_Summa_oplaty_14,lead_Summa_oplaty_15,lead_Tip_oplaty_11,lead_Tip_oplaty_12,lead_Tip_oplaty_13,lead_Tip_oplaty_14,lead_Tip_oplaty_15,lead_Otvety_s_kvizoprosa,lead_Data_2oj_konsultatsii,lead_Dozakrytie,lead_Otvety_s_kviza,lead_Operator,lead_Prichina_obraschenija,NULL AS lead_VCh,NULL AS lead_NCh,lead_Psihotip,lead_Situatsionnyj_blok,lead_Problemnyj_blok,lead_Izvlekajuschij_blok,lead_Nomer_linii_MANGO_OFFICE,NULL AS lead_ITOGO_OPLAChENO,lead_Data_pervichnogo_obraschenija,lead_Data_poseschenija_konsultatsii,lead_Data_okonchanija_lechenija,lead_Vid_oplaty_1,lead_Vid_oplaty_2,lead_Vid_oplaty_3,lead_Vid_oplaty_4,lead_Vid_oplaty_5,lead_Vid_oplaty_6,lead_Vid_oplaty_7,lead_Vid_oplaty_8,lead_Vid_oplaty_9,lead_Vid_oplaty_10,lead_Vid_oplaty_11,lead_Vid_oplaty_12,lead_Vid_oplaty_13,lead_Vid_oplaty_14,lead_Vid_oplaty_15,NULL AS lead_Sposob_oplaty,lead_Source_phone,lead_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,lead_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,lead_TsOV_Identifikator_kontakta,lead_Data_smeny_kuratora,lead_ID_predyduschego_kuratora,NULL AS klinika,contacts_1_id,contacts_1_name,contacts_1_responsible_user,contacts_1_contact_Dolzhnost,contacts_1_contact_Telefon,contacts_1_contact_Email,contacts_1_contact_Nomer_linii_MANGO_OFFICE,contacts_1_contact_Source_phone,contacts_1_contact_Whatsgroup_WZ,contacts_1_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_1_contact_TsOV_Identifikator_kontakta,NULL AS contacts_1_contact_Komment,contacts_1_companies_0_id,contacts_1_companies_0_name,contacts_1_companies_0_responsible_user,contacts_1_companies_0_company_Telefon,contacts_1_companies_0_company_Email,contacts_1_companies_0_company_Web,contacts_1_companies_0_company_Adres,contacts_0_contact_Instagram,contacts_0_contact_Instagram_WZ,contacts_0_contact_Profil,contacts_0_contact_Polzovatelskoe_soglashenie,contacts_0_contact_Kommentarij,contacts_0_companies_0_company_INN,contacts_0_companies_0_company_Sfera,contacts_0_companies_0_company_Oborot,contacts_0_companies_0_company_Kolichestvo_sotrudnikov,contacts_0_companies_0_company_Tip_programmy,companies_0_company_INN,companies_0_company_Sfera,companies_0_company_Oborot,companies_0_company_Kolichestvo_sotrudnikov,companies_0_company_Tip_programmy,lead_OSTATOK_K_OPLATE,lead_Sozdana_iz,lead_Obnovlena_iz,lead_Metrika_Jandeks,lead_Sotrudnik_otdela_servisa,lead_Klinika,lead_Data_prof_osmotra,lead_Kreditrassrochka,lead_Sotrudnik_vtorichnogo_otdela,lead_Problema,lead_Prichina_reshenija_konflikta_konflikta,lead_Data_oplaty_16,lead_Summa_oplaty_16,lead_Tip_oplaty_16,lead_Vid_oplaty_16,lead_Skoring_patsienta,lead_Skoring,lead_Data_oplaty_17,lead_Data_oplaty_18,lead_Data_oplaty_19,lead_Data_oplaty_20,lead_Summa_oplaty_17,lead_Summa_oplaty_18,lead_Summa_oplaty_19,lead_Summa_oplaty_20,lead_Tip_oplaty_17,lead_Tip_oplaty_18,lead_Tip_oplaty_19,lead_Tip_oplaty_20,lead_Vid_oplaty_17,lead_Vid_oplaty_18,lead_Vid_oplaty_19,lead_Vid_oplaty_20,lead_postbackurl,lead_Prichiny_konflikta,lead_Kommentarij,lead_Kategorija_patsienta,lead_Kvalifikatsija_KO,lead_UTM_SOURCE,lead_UTM_MEDIUM,lead_UTM_CAMPAIGN,lead_UTM_CONTENT,lead_UTM_TERM,lead_Summa_plan_oplaty_3,lead_Summa_plan_oplaty_4,lead_Summa_plan_oplaty_5,lead_Summa_plan_oplaty_6,lead_Data_plan_oplaty_3,lead_Data_plan_oplaty_4,lead_Data_plan_oplaty_5,lead_Data_plan_oplaty_6,lead_Data_oplaty_21,lead_Data_oplaty_22,lead_Data_oplaty_23,lead_Data_oplaty_24,lead_Data_oplaty_25,lead_Summa_oplaty_21,lead_Summa_oplaty_22,lead_Summa_oplaty_23,lead_Summa_oplaty_24,lead_Summa_oplaty_25,lead_Tip_oplaty_21,lead_Tip_oplaty_22,lead_Tip_oplaty_23,lead_Tip_oplaty_24,lead_Tip_oplaty_25,lead_Vid_oplaty_21,lead_Vid_oplaty_22,lead_Vid_oplaty_23,lead_Vid_oplaty_24,lead_Vid_oplaty_25,lead_TRANID,lead_FORMNAME,lead_FORMID,lead_REFERER,contacts_1_contact_Instagram,contacts_1_contact_Instagram_WZ,contacts_1_contact_Profil,contacts_1_contact_Polzovatelskoe_soglashenie,contacts_1_contact_Kommentarij,contacts_1_companies_0_company_INN,contacts_1_companies_0_company_Sfera,contacts_1_companies_0_company_Oborot,contacts_1_companies_0_company_Kolichestvo_sotrudnikov,contacts_1_companies_0_company_Tip_programmy,contacts_2_id,contacts_2_name,contacts_2_responsible_user,contacts_2_contact_Dolzhnost,contacts_2_contact_Telefon,contacts_2_contact_Email,contacts_2_contact_Nomer_linii_MANGO_OFFICE,contacts_2_contact_Instagram,contacts_2_contact_Instagram_WZ,contacts_2_contact_Profil,contacts_2_contact_Whatsgroup_WZ,contacts_2_contact_TsOV_Privlechen_kampaniej_ishodjaschego_obzvona,contacts_2_contact_TsOV_Identifikator_kampanii_ishodjaschego_obzvona,contacts_2_contact_TsOV_Identifikator_kontakta,contacts_2_contact_Source_phone,contacts_2_contact_Polzovatelskoe_soglashenie,contacts_2_contact_Kommentarij,contacts_2_companies_0_id,contacts_2_companies_0_name,contacts_2_companies_0_responsible_user,contacts_2_companies_0_company_Telefon,contacts_2_companies_0_company_Email,contacts_2_companies_0_company_Web,contacts_2_companies_0_company_Adres,contacts_2_companies_0_company_INN,contacts_2_companies_0_company_Sfera,contacts_2_companies_0_company_Oborot,contacts_2_companies_0_company_Kolichestvo_sotrudnikov,contacts_2_companies_0_company_Tip_programmy FROM {db_name}.spb
        """
        client.command(create_combined_query)

def create_user_tables(client, users_table):
    client.command(f"""
    CREATE TABLE IF NOT EXISTS {users_table} (
        `index` Int64,
        `date` Date,
        `oplata_summa` Nullable(Float64),
        `oplata_credit_summa` Nullable(Float64),
        `id` Nullable(Int64),
        `contacts_0_responsible_user` Nullable(String),
        `responsible_user` Nullable(String),
        `lead_PervichkaVtorichka` Nullable(String),
        `etap_sdelki` Nullable(String),
        `price` Nullable(Float64),
        `klinika` Nullable(String),
        `lead_klinika` Nullable(String),
        `lead_Konsdoktor_perv_doktor` Nullable(String),
        `lead_Data_1oj_konsultatsii` Nullable(Date),
        `leads_with_summa` Nullable(Int64),
        `leads_count` Nullable(Int64),
        `conversion` Nullable(Float64)
    ) ENGINE = MergeTree()
    ORDER BY `index`
    """)

def get_users_from_csv(needed_users):
    parent_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
    file_path = os.path.join(parent_dir, 'leads_csv/users.csv')
    
    with open(file_path, mode='r') as file:
        reader = csv.reader(file, delimiter=';')
        next(reader)
        
        for user, klinika, chat_id, monthly_plan in reader:
            needed_users.append(user)

def make_user_info_query(PervichkaVtorichka, needed_users, current_date, combined_table):
    oplata_summa_conditions = []
    '''
    Даты оплаты, если их станет больше - поменять значение в цикле
    '''
    for i in range(1, 26):
        oplata_summa_conditions.append(
            f"multiIf(lead_Data_oplaty_{i} = '{current_date}' AND lead_PervichkaVtorichka = '{PervichkaVtorichka}', lead_Summa_oplaty_{i}, '0')"
        )
    
    '''
    Даты преддполагаемых оплаты, если их станет больше - поменять значение в цикле
    '''
    credit_columns = [f"multiIf(lead_Data_plan_oplaty_{i} = '{current_date}', lead_Summa_plan_oplaty_{i}, '0')" for i in range(1, 7)]
    query = f"""
                SELECT 
                    users_info.summa,
                    users_info.credit,
                    ifNull(users_info.id, leads_count.id) AS id,
                    ifNull(users_info.contacts_0_responsible_user, leads_count.contacts_0_responsible_user) AS contacts_0_responsible_user,
                    leads_count.responsible_user,
                    ifNull(users_info.lead_PervichkaVtorichka, leads_count.lead_PervichkaVtorichka) AS lead_PervichkaVtorichka,
                    ifNull(users_info.etap_sdelki, leads_count.etap_sdelki) AS etap_sdelki,
					ifNull(users_info.price, leads_count.price) AS price,
					ifNull(users_info.klinika, leads_count.klinika) AS klinika,
					ifNull(users_info.lead_Klinika, leads_count.lead_Klinika) AS lead_Klinika,
					ifNull(users_info.lead_Konsdoktor_perv_doktor, leads_count.lead_Konsdoktor_perv_doktor) AS lead_Konsdoktor_perv_doktor,
					ifNull(users_info.lead_Data_1oj_konsultatsii, leads_count.lead_Data_1oj_konsultatsii) AS lead_Data_1oj_konsultatsii,
                    users_info.leads_with_summa,
                    leads_count.leads_count,
                    multiIf(leads_count.leads_count = 0, 0, FLOOR(users_info.leads_with_summa / leads_count.leads_count * 100, 1)) AS conversion
                FROM
                    (SELECT users_info.*, user_leads.leads_count FROM
                        (SELECT
                            id,
                            responsible_user,
                            lead_PervichkaVtorichka,
                            etap_sdelki,
                            price,
                            klinika,
                            lead_Klinika,
                            lead_Konsdoktor_perv_doktor,
                            lead_Data_1oj_konsultatsii,
                            contacts_0_responsible_user
                        FROM
                            {combined_table}
                        WHERE
                            responsible_user IN ('{"', '".join(needed_users)}')
                            AND created_at = '{current_date}'
                            AND lead_PervichkaVtorichka = '{PervichkaVtorichka}') AS users_info
                        LEFT JOIN
                        (SELECT responsible_user, COUNT(responsible_user) as leads_count FROM {combined_table} WHERE created_at = '{current_date}' AND lead_PervichkaVtorichka = '{PervichkaVtorichka}' GROUP BY responsible_user) AS user_leads
                        ON users_info.responsible_user = user_leads.responsible_user) AS leads_count
                    LEFT JOIN
                    (SELECT 
                        arraySum(x->ifNull(toFloat64(x), 0), [{', '.join(oplata_summa_conditions)}]) AS summa,
                        arraySum(x->ifNull(toFloat64(x), 0), [{', '.join(credit_columns)}]) AS credit,
                        id,
                        contacts_0_responsible_user,
                        responsible_user,
                        lead_PervichkaVtorichka,
                        etap_sdelki,
                        ifNull(toFloat64(price), 0) AS price,
                        klinika,
                        lead_Klinika,
                        lead_Konsdoktor_perv_doktor,
                        lead_Data_1oj_konsultatsii,
                        arrayCount(x->(ifNull(toFloat64(x), 0) <> 0), [{', '.join(oplata_summa_conditions)}]) AS leads_with_summa
                    FROM 
                        {combined_table}
                    WHERE 
                        lead_PervichkaVtorichka = '{PervichkaVtorichka}' AND ({" OR ".join([f"lead_Data_oplaty_{i} = '{current_date}'" for i in range(1, 26)])})) AS users_info
                    ON leads_count.responsible_user = users_info.responsible_user
            """

    return query

def fill_users_table(client, combined_table, users_table):
    needed_users = []
    current_date = datetime.now().date()
    transformed_data = []

    get_users_from_csv(needed_users)
    query = f"""
            SELECT * FROM ({make_user_info_query('Первичка', needed_users, current_date, combined_table)})
            UNION ALL
            SELECT * FROM ({make_user_info_query('Вторичка', needed_users, current_date, combined_table)})
        """

    result = client.query(query)
    max_index_query = f"SELECT MAX(`index`) FROM {users_table}"
    max_index = client.query(max_index_query)
    max_index = max_index.result_rows[0][0] if max_index.result_rows[0][0] else 0
    index = max_index + 1
    res = result.result_rows
    for row in res:
        transformed_row = (
            index,
            current_date,
            row[0],
            row[1],
            row[2],
            row[3],
            row[4],
            row[5],
            row[6],
            row[7],
            row[8],
            row[9],
            row[10],
            row[11],
            row[12],
            row[13],
            row[14],
        )
        index += 1

        transformed_data.append(transformed_row)

    if transformed_data:
        client.insert(users_table, transformed_data)

if __name__ == '__main__':
    logs_file_service = FileService('UploadCsvInClickhouseLogs')
    config_file_service = FileService('upload_csv_in_clickhouse_config.json')
    json_config = config_file_service.read_json_from_file()

    host = json_config.get('HOST', 'localhost')
    port = json_config.get('PORT', 8123)
    local_port = json_config.get('LOCAL_PORT', 9000)
    username = json_config.get('USERNAME', 'default')
    password = json_config.get('PASSWORD', '')
    db_name = json_config.get('DB_NAME', 'miatest')
    table_names = json_config.get('TABLE_NAMES', ['msc', 'spb'])
    combined_table = f'{db_name}.msc_spb'
    users_table = f'{db_name}.users'

    client = get_client(host=host, port=port, username=username, password=password)
    for table_name in table_names:
        parent_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
        file_path = os.path.join(parent_dir, f'leads_csv/{table_name}.csv')
        logs_file_service.write_log_file(f'Удаляем таблицу {table_name} из базы {db_name}')
        drop_query = f"DROP TABLE IF EXISTS {db_name}.{table_name}"
        try:
            client.command(drop_query)
            logs_file_service.write_log_file(f'Удалили таблицу {table_name} из базы {db_name}')
        except Exception as ex:
            logs_file_service.write_log_file(f'Ошибка удаления таблицы {table_name} из базы {db_name}: {ex}')
            continue
        
        logs_file_service.write_log_file(f'Создаём колонки для таблицы {table_name}')
        try:
            create_query = get_unique_types_in_columns(file_path)
            logs_file_service.write_log_file(f'Создали колонки "{create_query}" для таблицы {table_name}')
        except Exception as ex:
            logs_file_service.write_log_file(f'Ошибка создания колонок для таблицы {table_name}')

        logs_file_service.write_log_file(f'Создаём таблицу {table_name} в базу {db_name}')
        create_query = f'CREATE TABLE {db_name}.{table_name} ({create_query}) ENGINE = MergeTree() ORDER BY tuple()'
        try:
            client.command(create_query)
            logs_file_service.write_log_file(f'Создали таблицу {table_name} в базу {db_name}')
        except Exception as ex:
            logs_file_service.write_log_file(f'Ошибка создания таблицы {table_name} в базу {db_name}: {ex}')
            continue
        
        logs_file_service.write_log_file(f'Вставляем данные из {file_path} в таблицу {table_name} в базу {db_name}')
        try:
            import_data(db_name, table_name, file_path, username, password, local_port)
            logs_file_service.write_log_file(f'Вставили данные из {file_path} в таблицу {table_name} в базу {db_name}')
        except Exception as ex:
            logs_file_service.write_log_file(f'Ошибка вставки данных из {file_path} в таблицу {table_name} в базу {db_name}: {ex}')
            continue

    logs_file_service.write_log_file(f'Объединяем ранее созданные таблицы в базе {db_name}')
    try:
        create_or_truncate_combined_table(db_name, combined_table, client)
        logs_file_service.write_log_file(f'Объединили ранее созданные таблицы в базе {db_name}')
    except Exception as ex:
        logs_file_service.write_log_file(f'Ошибка объединения ранее созданных таблицы в базе {db_name}: {ex}')

    try:
        create_user_tables(client, users_table)
        logs_file_service.write_log_file(f'Создаём таблицу users в базу {db_name}')
    except Exception as ex:
        logs_file_service.write_log_file(f'Ошибка создания таблицы users в базу {db_name}: {ex}')

    try:
        fill_users_table(client, combined_table, users_table)
        logs_file_service.write_log_file(f'Заполняем таблицу users')
    except Exception as ex:
        logs_file_service.write_log_file(f'Ошибка заполнения таблицы users: {ex}')